# pandas Practice

Answer the questions below by writing some pandas code and using the dataframe saved to the `df` variable. The answer to the question should be in the cell's output!

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data/gapminder_all.csv", index_col="country")

In [4]:
df

,continent,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,...,pop_1962,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007
country,,,,,,,,,,,,,,,,,,,,,
Algeria,Africa,2449.008185,3013.976023,2550.816880,3246.991771,4182.663766,4910.416756,5745.160213,5681.358539,5023.216647,...,11000948.0,12760499.0,14760787.0,17152804.0,20033753.0,23254956.0,26298373.0,29072015.0,31287142,33333216
Angola,Africa,3520.610273,3827.940465,4269.276742,5522.776375,5473.288005,3008.647355,2756.953672,2430.208311,2627.845685,...,4826015.0,5247469.0,5894858.0,6162675.0,7016384.0,7874230.0,8735988.0,9875024.0,10866106,12420476
Benin,Africa,1062.752200,959.601080,949.499064,1035.831411,1085.796879,1029.161251,1277.897616,1225.856010,1191.207681,...,2151895.0,2427334.0,2761407.0,3168267.0,3641603.0,4243788.0,4981671.0,6066080.0,7026113,8078314
Botswana,Africa,851.241141,918.232535,983.653976,1214.709294,2263.611114,3214.857818,4551.142150,6205.883850,7954.111645,...,512764.0,553541.0,619351.0,781472.0,970347.0,1151184.0,1342614.0,1536536.0,1630347,1639131
Burkina Faso,Africa,543.255241,617.183465,722.512021,794.826560,854.735976,743.387037,807.198586,912.063142,931.752773,...,4919632.0,5127935.0,5433886.0,5889574.0,6634596.0,7586551.0,8878303.0,10352843.0,12251209,14326203
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Switzerland,Europe,14734.232750,17909.489730,20431.092700,22966.144320,27195.113040,26982.290520,28397.715120,30281.704590,31871.530300,...,5666000.0,6063000.0,6401400.0,6316424.0,6468126.0,6649942.0,6995447.0,7193761.0,7361757,7554661
Turkey,Europe,1969.100980,2218.754257,2322.869908,2826.356387,3450.696380,4269.122326,4241.356344,5089.043686,5678.348271,...,29788695.0,33411317.0,37492953.0,42404033.0,47328791.0,52881328.0,58179144.0,63047647.0,67308928,71158647
United Kingdom,Europe,9979.508487,11283.177950,12477.177070,14142.850890,15895.116410,17428.748460,18232.424520,21664.787670,22705.092540,...,53292000.0,54959000.0,56079000.0,56179000.0,56339704.0,56981620.0,57866349.0,58808266.0,59912431,60776238
Australia,Oceania,10039.595640,10949.649590,12217.226860,14526.124650,16788.629480,18334.197510,19477.009280,21888.889030,23424.766830,...,10794968.0,11872264.0,13177000.0,14074100.0,15184200.0,16257249.0,17481977.0,18565243.0,19546792,20434176
New Zealand,Oceania,10556.575660,12247.395320,13175.678000,14463.918930,16046.037280,16233.717700,17632.410400,19007.191290,18363.324940,...,2488550.0,2728150.0,2929100.0,3164900.0,3210650.0,3317166.0,3437674.0,3676187.0,3908037,4115771

Example: What was the GDP per cap of Turkey in 1972?

In [5]:
df.loc["Turkey", "gdpPercap_1972"]

3450.69638

Question #1: What was the population of Egypt in 1987?

In [6]:
df.loc['Egypt','pop_1987']

52799062.0

Question #2: What was the life expectancy in Singapore from 1952-2002?

In [7]:
df.loc['Singapore','lifeExp_1952':'lifeExp_2002']

lifeExp_1952    60.396
lifeExp_1957    63.179
lifeExp_1962    65.798
lifeExp_1967    67.946
lifeExp_1972    69.521
lifeExp_1977    70.795
lifeExp_1982     71.76
lifeExp_1987     73.56
lifeExp_1992    75.788
lifeExp_1997    77.158
lifeExp_2002     78.77
Name: Singapore, dtype: object

Question #3: Use describe() to show some summary statistics about GDP per cap for countries in the Americas

Bonus: display each year as a row and each summary statistic as a column

In [17]:
mask = df['continent'] == 'Americas'
df_amer = df[mask]
df_amer.loc[:,'gdpPercap_1952':'gdpPercap_2007'].describe().T

,count,mean,std,min,25%,50%,75%,max
gdpPercap_1952,25.0,4079.062552,3001.727522,1397.717137,2428.237769,3048.302900,3939.978789,13990.48208
gdpPercap_1957,25.0,4616.043733,3312.381083,1544.402995,2487.365989,3780.546651,4756.525781,14847.12712
gdpPercap_1962,25.0,4901.541870,3421.740569,1662.137359,2750.364446,4086.114078,5180.755910,16173.14586
gdpPercap_1967,25.0,5668.253496,4160.885560,1452.057666,3242.531147,4643.393534,5788.093330,19530.36557
gdpPercap_1972,25.0,6491.334139,4754.404329,1654.456946,4031.408271,5305.445256,6809.406690,21806.03594
gdpPercap_1977,25.0,7352.007126,5355.602518,1874.298931,4756.763836,6281.290855,7674.929108,24072.63213
gdpPercap_1982,25.0,7506.737088,5530.490471,2011.159549,4258.503604,6434.501797,8997.897412,25009.55914
gdpPercap_1987,25.0,7793.400261,6665.039509,1823.015995,4140.442097,6360.943444,7807.095818,29884.35041
gdpPercap_1992,25.0,8044.934406,7047.089191,1456.309517,4439.450840,6618.743050,8137.004775,32003.93224
gdpPercap_1997,25.0,8889.300863,7874.225145,1341.726931,4684.313807,7113.692252,9767.297530,35767.43303
gdpPercap_2002,25.0,9287.677107,8895.817785,1270.364932,4858.347495,6994.774861,8797.640716,39097.09955
gdpPercap_2007,25.0,11003.031625,9713.209302,1201.637154,5728.353514,8948.102923,11977.574960,42951.65309

Question #4: How many countries are in each continent?

In [20]:
df.groupby("continent").count()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,...,pop_1967,pop_1972,pop_1977,pop_1982,pop_1987,pop_1992,pop_1997,pop_2002,pop_2007,country
continent,,,,,,,,,,,,,,,,,,,,,
Africa,52,52,52,52,52,52,52,52,52,52,...,52,52,52,52,52,52,52,52,52,52
Americas,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,25
Asia,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
Europe,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
Oceania,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

Question #5: First, find the minimum life expectancies for all countries with a higher than average GDP (for that year). Then, find the maximum life expectancies for all countries with a lower than average GDP (for that year)

In [21]:
df_gdp = df.loc[:,'gdpPercap_1952':'gdpPercap_2007']
mask = df_gdp > df_gdp.mean()
df_gdp[mask]

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Algeria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Angola,NaN,NaN,NaN,5522.776375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11003.60508,12569.85177
Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Switzerland,14734.232750,17909.48973,20431.09270,22966.144320,27195.11304,26982.29052,28397.71512,30281.70459,31871.53030,32135.32301,34480.95771,37506.41907
Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,9979.508487,11283.17795,12477.17707,14142.850890,15895.11641,17428.74846,18232.42452,21664.78767,22705.09254,26074.53136,29478.99919,33203.26128
Australia,10039.595640,10949.64959,12217.22686,14526.124650,16788.62948,18334.19751,19477.00928,21888.88903,23424.76683,26997.93657,30687.75473,34435.36744
New Zealand,10556.575660,12247.39532,13175.67800,14463.918930,16046.03728,16233.71770,17632.41040,19007.19129,18363.32494,21050.41377,23189.80135,25185.00911

In [24]:
# How much did Turkey's population grow between 1967-1987?

df.loc['Turkey','pop_1967':'pop_1987']

pop_1967    33411317.0
pop_1972    37492953.0
pop_1977    42404033.0
pop_1982    47328791.0
pop_1987    52881328.0
Name: Turkey, dtype: object

In [25]:
df.loc['Turkey','pop_1987'] - df.loc['Turkey','pop_1967']

19470011.0